In [77]:
import pandas as pd
import numpy as np
import re
from nltk import pos_tag
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from collections import Counter

In [2]:
jobs = pd.read_csv('jobs.csv')

In [3]:
len(jobs)

251

In [4]:
jobs.head(20)

,Job ID,Title,Company Name,Company Location,Description
0,216832519,Senior Data Scientist at CyberCoders\r\n,CyberCoders,"Santa Monica, CA",<span id='TrackingJobBody' name='TrackingJobBo...
1,216746616,"Data Scientist - Python, Data Collection, Mach...",CyberCoders,"San Francisco, CA",<span id='TrackingJobBody' name='TrackingJobBo...
2,216832221,Data Scientist at CyberCoders\r\n,CyberCoders,"Los Angeles, CA 90024",<span id='TrackingJobBody' name='TrackingJobBo...
3,d0bffb50-18df-4e9a-8d9a-6157a427dcd0,Data Science Communications Manager at IBM\r\n,IBM,"San Jose, CA 95192",Introduction <br>Uncover and transform insight...
4,216778552,Senior Data Scientist at CyberCoders\r\n,CyberCoders,"Sunnyvale, CA 94085",<span id='TrackingJobBody' name='TrackingJobBo...
5,216718556,"Chief Data/BI Scientist - SQL, Python/R, Spark...",CyberCoders,"Santa Monica, CA 90401",<span id='TrackingJobBody' name='TrackingJobBo...
6,216747143,"Sr Data Scientist - Python, H2O, pandas at Cyb...",CyberCoders,"San Jose, CA 95110",<span id='TrackingJobBody' name='TrackingJobBo...
7,216215875,"Data Science Engineer at Tentek, Inc\r\n","Tentek, Inc","Torrance, CA",<span id='TrackingJobBody' name='TrackingJobBo...
8,216801766,"Data Scientist - Python, Data Collection, Mach...",CyberCoders,"San Francisco, CA",<span id='TrackingJobBody' name='TrackingJobBo...
9,216779011,Data Scientist - Artificial Intelligence at Cy...,CyberCoders,"Palo Alto, CA 94301",<span id='TrackingJobBody' name='TrackingJobBo...
10,216779329,"Data Scientist - Machince Learning, NLP, Resea...",CyberCoders,"Mountain View, CA",<span id='TrackingJobBody' name='TrackingJobBo...
11,216779712,"Lead Data Scientist - CNN, Deep Learning - REL...",CyberCoders,"West Hollywood, CA 90038",<span id='TrackingJobBody' name='TrackingJobBo...
12,216185484,Data Scientist - Principal from Genuent LLC,Genuent LLC,"Burbank, CA 91506",<span id='TrackingJobBody' name='TrackingJobBo...
13,216800027,"Data Scientist - Real Pay, Real Equity play! a...",CyberCoders,"Santa Monica, CA 90401",<span id='TrackingJobBody' name='TrackingJobBo...
14,216652251,Data Scientist/Analyst from Digital Intelligen...,Digital Intelligence Systems,"Oakland, CA 94612",<span id='TrackingJobBody' name='TrackingJobBo...
15,216717812,Contract Neo4j Data Engineer at CyberCoders\r\n,CyberCoders,"Mountain View, CA 94041",<span id='TrackingJobBody' name='TrackingJobBo...
16,216833735,Bioinformatics Production Engineer at CyberCod...,CyberCoders,"Redwood City, CA",<span id='TrackingJobBody' name='TrackingJobBo...
17,216746528,Director of Software Operations (Reliability &...,CyberCoders,"San Carlos, CA 94070",<span id='TrackingJobBody' name='TrackingJobBo...
18,216717811,"Full Stack Developer - Angular, Typescript, GC...",CyberCoders,"El Segundo, CA 90245",<span id='TrackingJobBody' name='TrackingJobBo...
19,216718120,"Senior Data Engineer - Spark, Python, vision a...",CyberCoders,"Mountain View, CA 94041",<span id='TrackingJobBody' name='TrackingJobBo...

In [5]:
jobs_data = jobs.loc[jobs['Title'].str.contains('Data'), :]

In [6]:
jobs_data.head()

,Job ID,Title,Company Name,Company Location,Description
0,216832519,Senior Data Scientist at CyberCoders\r\n,CyberCoders,"Santa Monica, CA",<span id='TrackingJobBody' name='TrackingJobBo...
1,216746616,"Data Scientist - Python, Data Collection, Mach...",CyberCoders,"San Francisco, CA",<span id='TrackingJobBody' name='TrackingJobBo...
2,216832221,Data Scientist at CyberCoders\r\n,CyberCoders,"Los Angeles, CA 90024",<span id='TrackingJobBody' name='TrackingJobBo...
3,d0bffb50-18df-4e9a-8d9a-6157a427dcd0,Data Science Communications Manager at IBM\r\n,IBM,"San Jose, CA 95192",Introduction <br>Uncover and transform insight...
4,216778552,Senior Data Scientist at CyberCoders\r\n,CyberCoders,"Sunnyvale, CA 94085",<span id='TrackingJobBody' name='TrackingJobBo...

In [7]:
jobs['Description'][0]

'<span id=\'TrackingJobBody\' name=\'TrackingJobBody\'><div class="section-data" data-section="1"><!--START_SECTION_1-->Are you a Senior Data Scientist who dreams of working for a fun and energetic environment?  Are you working with the latest in complex data products and data models?  If so, please read on!<br><br><br>We are the fastest growing tech company rolling up mobile applications in the user generated content space.  We are quickly becoming a leader in the Programmatic Ads space (a $60B a year industry in the U.S.)  We outperform the market by 30%!<br><br> <br><br>We are looking to bring on a Senior Data Scientist to help create and design cutting edge data models to help improve on identifying malicious actors and optimize our end user experience.<!--END_SECTION_1--></div><!--START_SECTION_2--><!--END_SECTION_2--><h4 class="section-title">What You Will Be Doing</h4><div class="section-data section-data-title" data-section="5"><!--START_SECTION_5-->- Design and create cutting edge data models to identify malicious actors and spam to optimize user experience<br>- Improve system performance to help create automaton frameworks to approve/delete content<br><br>- Work with cross-functional teams to create better data manipulation techniques and define statistical analytics/models<br><br>- Help overcome analytical issues and help define scalable processes with data and engineering teams<br><br>- Collaborate with internal stakeholders and business teams to ensure goals are aligned with project intiatives<!--END_SECTION_5--></div><h4 class="section-title">What You Need for this Position</h4><div class="section-data section-data-title" data-section="7"><!--START_SECTION_7-->The Senior Data Scientist must have at least 5 years of post-graduate expeience and be familiar with:<br><br><br>- Background in data engineering with highly scaled data systems<br><br>- Experience with deploying and supporting projects in production<br><br>- Solid background working with Python and SQL languages<br><br>- Experience with large scale database frameworks (MySQL, PostgreSQL, MongoDB, DynamoDB, etc.)<br><br>- Familiar with cloud services platforms (Google DataFlow, BigQuery, RedShift, DataBricks, Apache Samza, etc.)<br><br>- BS or MS degree in Computer Science preferred<!--END_SECTION_7--></div><h4 class="section-title">What\'s In It for You</h4><div class="section-data section-data-title" data-section="8"><!--START_SECTION_8-->- We pay 100% of medical, dental, and vision premiums for full-time employees and their dependents<br>- Fast moving environment with ability to impact corporate strategy<br><br>- Open vacation policy; we dont count days<!--END_SECTION_8--></div><div class="section-data" data-section="9"><!--START_SECTION_9-->So, if you are a Senior Data Scientist with experience building complex data systems and a passion for consumer facing technology, we want to see your resume right away!<!--END_SECTION_9--></div><br><br><br>CyberCoders will consider for Employment in the City of Los Angeles qualified Applicants with Criminal Histories in a manner consistent with the requirements of the Los Angeles Fair Chance Initiative for Hiring (Ban the Box) Ordinance.</span>'

In [8]:
TAG_RE = re.compile(r'<[^>]+>')

In [11]:
my_string = TAG_RE.sub('', jobs['Description'][0])
my_string

"Are you a Senior Data Scientist who dreams of working for a fun and energetic environment?  Are you working with the latest in complex data products and data models?  If so, please read on!We are the fastest growing tech company rolling up mobile applications in the user generated content space.  We are quickly becoming a leader in the Programmatic Ads space (a $60B a year industry in the U.S.)  We outperform the market by 30%! We are looking to bring on a Senior Data Scientist to help create and design cutting edge data models to help improve on identifying malicious actors and optimize our end user experience.What You Will Be Doing- Design and create cutting edge data models to identify malicious actors and spam to optimize user experience- Improve system performance to help create automaton frameworks to approve/delete content- Work with cross-functional teams to create better data manipulation techniques and define statistical analytics/models- Help overcome analytical issues and help define scalable processes with data and engineering teams- Collaborate with internal stakeholders and business teams to ensure goals are aligned with project intiativesWhat You Need for this PositionThe Senior Data Scientist must have at least 5 years of post-graduate expeience and be familiar with:- Background in data engineering with highly scaled data systems- Experience with deploying and supporting projects in production- Solid background working with Python and SQL languages- Experience with large scale database frameworks (MySQL, PostgreSQL, MongoDB, DynamoDB, etc.)- Familiar with cloud services platforms (Google DataFlow, BigQuery, RedShift, DataBricks, Apache Samza, etc.)- BS or MS degree in Computer Science preferredWhat's In It for You- We pay 100% of medical, dental, and vision premiums for full-time employees and their dependents- Fast moving environment with ability to impact corporate strategy- Open vacation policy; we dont count daysSo, if you are a Senior Data Scientist with experience building complex data systems and a passion for consumer facing technology, we want to see your resume right away!CyberCoders will consider for Employment in the City of Los Angeles qualified Applicants with Criminal Histories in a manner consistent with the requirements of the Los Angeles Fair Chance Initiative for Hiring (Ban the Box) Ordinance."

In [19]:
pos_tokens = pos_tag(word_tokenize(my_string))

In [20]:
pos_tokens

[('Are', 'NNP'),
 ('you', 'PRP'),
 ('a', 'DT'),
 ('Senior', 'NNP'),
 ('Data', 'NNP'),
 ('Scientist', 'NNP'),
 ('who', 'WP'),
 ('dreams', 'VBZ'),
 ('of', 'IN'),
 ('working', 'VBG'),
 ('for', 'IN'),
 ('a', 'DT'),
 ('fun', 'NN'),
 ('and', 'CC'),
 ('energetic', 'JJ'),
 ('environment', 'NN'),
 ('?', '.'),
 ('Are', 'NNP'),
 ('you', 'PRP'),
 ('working', 'VBG'),
 ('with', 'IN'),
 ('the', 'DT'),
 ('latest', 'JJS'),
 ('in', 'IN'),
 ('complex', 'JJ'),
 ('data', 'NN'),
 ('products', 'NNS'),
 ('and', 'CC'),
 ('data', 'NNS'),
 ('models', 'NNS'),
 ('?', '.'),
 ('If', 'IN'),
 ('so', 'RB'),
 (',', ','),
 ('please', 'VB'),
 ('read', 'VB'),
 ('on', 'IN'),
 ('!', '.'),
 ('We', 'PRP'),
 ('are', 'VBP'),
 ('the', 'DT'),
 ('fastest', 'JJS'),
 ('growing', 'VBG'),
 ('tech', 'JJ'),
 ('company', 'NN'),
 ('rolling', 'VBG'),
 ('up', 'RP'),
 ('mobile', 'JJ'),
 ('applications', 'NNS'),
 ('in', 'IN'),
 ('the', 'DT'),
 ('user', 'NN'),
 ('generated', 'VBD'),
 ('content', 'JJ'),
 ('space', 'NN'),
 ('.', '.'),
 ('We', 'PRP'),
 ('are', 'VBP'),
 ('quickly', 'RB'),
 ('becoming', 'VBG'),
 ('a', 'DT'),
 ('leader', 'NN'),
 ('in', 'IN'),
 ('the', 'DT'),
 ('Programmatic', 'NNP'),
 ('Ads', 'NNP'),
 ('space', 'NN'),
 ('(', '('),
 ('a', 'DT'),
 ('$', '$'),
 ('60B', 'CD'),
 ('a', 'DT'),
 ('year', 'NN'),
 ('industry', 'NN'),
 ('in', 'IN'),
 ('the', 'DT'),
 ('U.S.', 'NNP'),
 (')', ')'),
 ('We', 'PRP'),
 ('outperform', 'VBP'),
 ('the', 'DT'),
 ('market', 'NN'),
 ('by', 'IN'),
 ('30', 'CD'),
 ('%', 'NN'),
 ('!', '.'),
 ('We', 'PRP'),
 ('are', 'VBP'),
 ('looking', 'VBG'),
 ('to', 'TO'),
 ('bring', 'VB'),
 ('on', 'IN'),
 ('a', 'DT'),
 ('Senior', 'NNP'),
 ('Data', 'NNP'),
 ('Scientist', 'NNP'),
 ('to', 'TO'),
 ('help', 'VB'),
 ('create', 'VB'),
 ('and', 'CC'),
 ('design', 'VB'),
 ('cutting', 'VBG'),
 ('edge', 'NN'),
 ('data', 'NNS'),
 ('models', 'NNS'),
 ('to', 'TO'),
 ('help', 'VB'),
 ('improve', 'VB'),
 ('on', 'IN'),
 ('identifying', 'VBG'),
 ('malicious', 'JJ'),
 ('actors', 'NNS'),
 ('and', 'CC'),
 ('optimize', 'VB'),
 ('our', 'PRP$'),
 ('end', 'NN'),
 ('user', 'NN'),
 ('experience.What', 'IN'),
 ('You', 'PRP'),
 ('Will', 'MD'),
 ('Be', 'VB'),
 ('Doing-', 'NNP'),
 ('Design', 'NNP'),
 ('and', 'CC'),
 ('create', 'VB'),
 ('cutting', 'VBG'),
 ('edge', 'NN'),
 ('data', 'NNS'),
 ('models', 'NNS'),
 ('to', 'TO'),
 ('identify', 'VB'),
 ('malicious', 'JJ'),
 ('actors', 'NNS'),
 ('and', 'CC'),
 ('spam', 'NN'),
 ('to', 'TO'),
 ('optimize', 'VB'),
 ('user', 'JJ'),
 ('experience-', 'JJ'),
 ('Improve', 'NNP'),
 ('system', 'NN'),
 ('performance', 'NN'),
 ('to', 'TO'),
 ('help', 'VB'),
 ('create', 'VB'),
 ('automaton', 'JJ'),
 ('frameworks', 'NNS'),
 ('to', 'TO'),
 ('approve/delete', 'VB'),
 ('content-', 'JJ'),
 ('Work', 'NN'),
 ('with', 'IN'),
 ('cross-functional', 'JJ'),
 ('teams', 'NNS'),
 ('to', 'TO'),
 ('create', 'VB'),
 ('better', 'JJR'),
 ('data', 'NNS'),
 ('manipulation', 'NN'),
 ('techniques', 'NNS'),
 ('and', 'CC'),
 ('define', 'VB'),
 ('statistical', 'JJ'),
 ('analytics/models-', 'JJ'),
 ('Help', 'NNP'),
 ('overcome', 'VB'),
 ('analytical', 'JJ'),
 ('issues', 'NNS'),
 ('and', 'CC'),
 ('help', 'VB'),
 ('define', 'VB'),
 ('scalable', 'JJ'),
 ('processes', 'NNS'),
 ('with', 'IN'),
 ('data', 'NNS'),
 ('and', 'CC'),
 ('engineering', 'NN'),
 ('teams-', 'JJ'),
 ('Collaborate', 'NNP'),
 ('with', 'IN'),
 ('internal', 'JJ'),
 ('stakeholders', 'NNS'),
 ('and', 'CC'),
 ('business', 'NN'),
 ('teams', 'NNS'),
 ('to', 'TO'),
 ('ensure', 'VB'),
 ('goals', 'NNS'),
 ('are', 'VBP'),
 ('aligned', 'VBN'),
 ('with', 'IN'),
 ('project', 'NN'),
 ('intiativesWhat', 'IN'),
 ('You', 'PRP'),
 ('Need', 'VBP'),
 ('for', 'IN'),
 ('this', 'DT'),
 ('PositionThe', 'NNP'),
 ('Senior', 'NNP'),
 ('Data', 'NNP'),
 ('Scientist', 'NNP'),
 ('must', 'MD'),
 ('have', 'VB'),
 ('at', 'IN'),
 ('least', 'JJS'),
 ('5', 'CD'),
 ('years', 'NNS'),
 ('of', 'IN'),
 ('post-graduate', 'JJ'),
 ('expeience', 'NN'),
 ('and', 'CC'),
 ('be', 'VB'),
 ('familiar', 'JJ'),
 ('with', 'IN'),
 (':', ':'),
 ('-', ':'),
 ('Background', 'NN'),
 ('in', 'IN'),
 ('data', 'NNS'),
 ('engineering', 'NN'),
 ('with', 'IN'),
 ('highly', 'RB'),
 ('scaled', 'VBN'),
 ('data', 'NNS'),
 ('systems-', 'JJ'),
 ('Experience', 'NN'),
 ('with', 'IN'),
 ('deploying', 'NN'),
 ('and', 'CC'),
 ('supporting', 'VBG'),
 ('projects', 'NNS'),
 ('in', 'IN'),
 ('production-', 'JJ'),
 ('Solid', 'NNP'),
 ('background', 'NN'),
 ('working', 'VBG'),
 ('with', 'IN'),
 ('Python', 'NNP'),
 ('and', 'CC'),
 ('SQL', 'NNP'),
 ('languages-', 'JJ'),
 ('Experience', 'NN'),
 ('with', 'IN'),
 ('large', 'JJ'),
 ('scale', 'JJ'),
 ('database', 'NN'),
 ('frameworks', 'NNS'),
 ('(', '('),
 ('MySQL', 'NNP'),
 (',', ','),
 ('PostgreSQL', 'NNP'),
 (',', ','),
 ('MongoDB', 'NNP'),
 (',', ','),
 ('DynamoDB', 'NNP'),
 (',', ','),
 ('etc', 'FW'),
 ('.', '.'),
 (')', ')'),
 ('-', ':'),
 ('Familiar', 'NN'),
 ('with', 'IN'),
 ('cloud', 'NN'),
 ('services', 'NNS'),
 ('platforms', 'NNS'),
 ('(', '('),
 ('Google', 'NNP'),
 ('DataFlow', 'NNP'),
 (',', ','),
 ('BigQuery', 'NNP'),
 (',', ','),
 ('RedShift', 'NNP'),
 (',', ','),
 ('DataBricks', 'NNP'),
 (',', ','),
 ('Apache', 'NNP'),
 ('Samza', 'NNP'),
 (',', ','),
 ('etc', 'FW'),
 ('.', '.'),
 (')', ')'),
 ('-', ':'),
 ('BS', 'NN'),
 ('or', 'CC'),
 ('MS', 'NNP'),
 ('degree', 'VBP'),
 ('in', 'IN'),
 ('Computer', 'NNP'),
 ('Science', 'NNP'),
 ('preferredWhat', 'WP'),
 ("'s", 'VBZ'),
 ('In', 'IN'),
 ('It', 'PRP'),
 ('for', 'IN'),
 ('You-', 'NNP'),
 ('We', 'PRP'),
 ('pay', 'VBP'),
 ('100', 'CD'),
 ('%', 'NN'),
 ('of', 'IN'),
 ('medical', 'JJ'),
 (',', ','),
 ('dental', 'JJ'),
 (',', ','),
 ('and', 'CC'),
 ('vision', 'NN'),
 ('premiums', 'NNS'),
 ('for', 'IN'),
 ('full-time', 'JJ'),
 ('employees', 'NNS'),
 ('and', 'CC'),
 ('their', 'PRP$'),
 ('dependents-', 'JJ'),
 ('Fast', 'NNP'),
 ('moving', 'VBG'),
 ('environment', 'NN'),
 ('with', 'IN'),
 ('ability', 'NN'),
 ('to', 'TO'),
 ('impact', 'VB'),
 ('corporate', 'JJ'),
 ('strategy-', 'JJ'),
 ('Open', 'NNP'),
 ('vacation', 'NN'),
 ('policy', 'NN'),
 (';', ':'),
 ('we', 'PRP'),
 ('dont', 'VBP'),
 ('count', 'JJ'),
 ('daysSo', 'NN'),
 (',', ','),
 ('if', 'IN'),
 ('you', 'PRP'),
 ('are', 'VBP'),
 ('a', 'DT'),
 ('Senior', 'NNP'),
 ('Data', 'NNP'),
 ('Scientist', 'NNP'),
 ('with', 'IN'),
 ('experience', 'NN'),
 ('building', 'NN'),
 ('complex', 'JJ'),
 ('data', 'NN'),
 ('systems', 'NNS'),
 ('and', 'CC'),
 ('a', 'DT'),
 ('passion', 'NN'),
 ('for', 'IN'),
 ('consumer', 'NN'),
 ('facing', 'NN'),
 ('technology', 'NN'),
 (',', ','),
 ('we', 'PRP'),
 ('want', 'VBP'),
 ('to', 'TO'),
 ('see', 'VB'),
 ('your', 'PRP$'),
 ('resume', 'VB'),
 ('right', 'JJ'),
 ('away', 'RB'),
 ('!', '.'),
 ('CyberCoders', 'NNPS'),
 ('will', 'MD'),
 ('consider', 'VB'),
 ('for', 'IN'),
 ('Employment', 'NN'),
 ('in', 'IN'),
 ('the', 'DT'),
 ('City', 'NNP'),
 ('of', 'IN'),
 ('Los', 'NNP'),
 ('Angeles', 'NNP'),
 ('qualified', 'VBD'),
 ('Applicants', 'NNS'),
 ('with', 'IN'),
 ('Criminal', 'NNP'),
 ('Histories', 'NNP'),
 ('in', 'IN'),
 ('a', 'DT'),
 ('manner', 'NN'),
 ('consistent', 'JJ'),
 ('with', 'IN'),
 ('the', 'DT'),
 ('requirements', 'NNS'),
 ('of', 'IN'),
 ('the', 'DT'),
 ('Los', 'NNP'),
 ('Angeles', 'NNP'),
 ('Fair', 'NNP'),
 ('Chance', 'NNP'),
 ('Initiative', 'NNP'),
 ('for', 'IN'),
 ('Hiring', 'NNP'),
 ('(', '('),
 ('Ban', 'NNP'),
 ('the', 'DT'),
 ('Box', 'NNP'),
 (')', ')'),
 ('Ordinance', 'NN'),
 ('.', '.')]

In [39]:
len(pos_tokens)

400

In [40]:
nouns = []

for tok in pos_tokens:
    if ( tok[1] in ('NN', 'NNS', 'NNP', 'NNPS') ) and ( tok[0].lower() not in stopwords.words('english')):
        nouns.append(tok[0].lower())

In [41]:
nouns

['senior',
 'data',
 'scientist',
 'fun',
 'environment',
 'data',
 'products',
 'data',
 'models',
 'company',
 'applications',
 'user',
 'space',
 'leader',
 'programmatic',
 'ads',
 'space',
 'year',
 'industry',
 'u.s.',
 'market',
 '%',
 'senior',
 'data',
 'scientist',
 'edge',
 'data',
 'models',
 'actors',
 'end',
 'user',
 'doing-',
 'design',
 'edge',
 'data',
 'models',
 'actors',
 'spam',
 'improve',
 'system',
 'performance',
 'frameworks',
 'work',
 'teams',
 'data',
 'manipulation',
 'techniques',
 'help',
 'issues',
 'processes',
 'data',
 'engineering',
 'collaborate',
 'stakeholders',
 'business',
 'teams',
 'goals',
 'project',
 'positionthe',
 'senior',
 'data',
 'scientist',
 'years',
 'expeience',
 'background',
 'data',
 'engineering',
 'data',
 'experience',
 'deploying',
 'projects',
 'solid',
 'background',
 'python',
 'sql',
 'experience',
 'database',
 'frameworks',
 'mysql',
 'postgresql',
 'mongodb',
 'dynamodb',
 'familiar',
 'cloud',
 'services',
 'platforms',
 'google',
 'dataflow',
 'bigquery',
 'redshift',
 'databricks',
 'apache',
 'samza',
 'bs',
 'ms',
 'computer',
 'science',
 'you-',
 '%',
 'vision',
 'premiums',
 'employees',
 'fast',
 'environment',
 'ability',
 'open',
 'vacation',
 'policy',
 'daysso',
 'senior',
 'data',
 'scientist',
 'experience',
 'building',
 'data',
 'systems',
 'passion',
 'consumer',
 'facing',
 'technology',
 'cybercoders',
 'employment',
 'city',
 'los',
 'angeles',
 'applicants',
 'criminal',
 'histories',
 'manner',
 'requirements',
 'los',
 'angeles',
 'fair',
 'chance',
 'initiative',
 'hiring',
 'ban',
 'box',
 'ordinance']

In [42]:
len(nouns)

139

In [45]:
word_count = {i:nouns.count(i) for i in set(nouns)}

In [51]:
sorted(word_count.items(), key = lambda kv:(kv[1], kv[0]), reverse = True)

[('data', 13),
 ('senior', 4),
 ('scientist', 4),
 ('models', 3),
 ('experience', 3),
 ('user', 2),
 ('teams', 2),
 ('space', 2),
 ('los', 2),
 ('frameworks', 2),
 ('environment', 2),
 ('engineering', 2),
 ('edge', 2),
 ('background', 2),
 ('angeles', 2),
 ('actors', 2),
 ('%', 2),
 ('you-', 1),
 ('years', 1),
 ('year', 1),
 ('work', 1),
 ('vision', 1),
 ('vacation', 1),
 ('u.s.', 1),
 ('technology', 1),
 ('techniques', 1),
 ('systems', 1),
 ('system', 1),
 ('stakeholders', 1),
 ('sql', 1),
 ('spam', 1),
 ('solid', 1),
 ('services', 1),
 ('science', 1),
 ('samza', 1),
 ('requirements', 1),
 ('redshift', 1),
 ('python', 1),
 ('projects', 1),
 ('project', 1),
 ('programmatic', 1),
 ('products', 1),
 ('processes', 1),
 ('premiums', 1),
 ('postgresql', 1),
 ('positionthe', 1),
 ('policy', 1),
 ('platforms', 1),
 ('performance', 1),
 ('passion', 1),
 ('ordinance', 1),
 ('open', 1),
 ('mysql', 1),
 ('ms', 1),
 ('mongodb', 1),
 ('market', 1),
 ('manner', 1),
 ('manipulation', 1),
 ('leader', 1),
 ('issues', 1),
 ('initiative', 1),
 ('industry', 1),
 ('improve', 1),
 ('histories', 1),
 ('hiring', 1),
 ('help', 1),
 ('google', 1),
 ('goals', 1),
 ('fun', 1),
 ('fast', 1),
 ('familiar', 1),
 ('fair', 1),
 ('facing', 1),
 ('expeience', 1),
 ('end', 1),
 ('employment', 1),
 ('employees', 1),
 ('dynamodb', 1),
 ('doing-', 1),
 ('design', 1),
 ('deploying', 1),
 ('daysso', 1),
 ('dataflow', 1),
 ('databricks', 1),
 ('database', 1),
 ('cybercoders', 1),
 ('criminal', 1),
 ('consumer', 1),
 ('computer', 1),
 ('company', 1),
 ('collaborate', 1),
 ('cloud', 1),
 ('city', 1),
 ('chance', 1),
 ('business', 1),
 ('building', 1),
 ('bs', 1),
 ('box', 1),
 ('bigquery', 1),
 ('ban', 1),
 ('applications', 1),
 ('applicants', 1),
 ('apache', 1),
 ('ads', 1),
 ('ability', 1)]


1
NN
NNS
NNP
NNPS


2
JJ
JJR
JJS
VB
VBD
VBG
VBN
VBP
VBZ


?
FW
LS
PDT

## Apply to Whole Dataset

In [60]:
job_des = jobs['Description']

In [61]:
job_des = job_des.apply(lambda x: TAG_RE.sub(' ', x))

In [62]:
job_des

0         Are you a Senior Data Scientist who dreams ...
1          Job Title:  Data Scientist  Location:  San...
2         If you are a Data Scientist/Machine Learnin...
3      Introduction  Uncover and transform insights i...
4         If you are a Senior Data Scientist with exp...
                             ...
246        DATA SCIENTIST  Company:  Trib3.com, Inc. ...
247     Our client, a music streaming service located...
248     Senior Data Scientist professional needed at ...
249     TECHNOLOGY  \tEricsson Inc. has an opening in...
250      A client of Sharp Decisions Inc. is actively...
Name: Description, Length: 251, dtype: object

In [63]:
job_des[250]

"  A client of Sharp Decisions Inc. is actively looking to bring on a Data Scientist to be based in Torrance, California.&nbsp;   Job Description   This role will unlock new opportunities for innovation by:   Exploring data to discover hidden relationships and trends  Developing and validating predictive mathematical models  Creating and presenting interactive data visualizations to influence key decisions with strong data-driven rationale  Deconstructing complicated data flows and processes and translating them into easy to understand diagrams for executive audiences  Analyzing and quantifying customer feedback using natural language processing tools  Developing algorithms to enhance our customers' experiences or improve our internal processes    Academic/Experience/Competency    Bachelor's or graduate degree in science, technology, engineering or mathematics.  Professional knowledge or experience with data programming languages (SQL, Python, R, etc.)  Proficiency with abstract data structures and algorithms  Proficiency with differential equations and linear algebra  Strong proficiency in statistics and advanced analytic topics (regression, clustering, etc.)  Proficiency in Excel (ability to write advanced functions, VBA knowledge is a plus)  Experience with data visualization software and libraries such as Tableau and D3.js  Experience building analytic models, particularly using predictive techniques  Experience with machine learning tools  Experience with creating data flow diagrams    Daily Tasks Performed    Explore and analyze data to discover insights  Translate complex data relationships and findings into compelling stories using easy to understand data visualizations  Propose new data processing methods to improve our products and services  Develop and maintain data dictionaries    Wants    Experience with web technologies HTML/CSS/JS,  Familiarity with React.js framework  Experience with mobile app development   "

In [64]:
job_tokens = job_des.apply(lambda x: pos_tag(word_tokenize(x)))

In [65]:
job_tokens

0      [(Are, NNP), (you, PRP), (a, DT), (Senior, NNP...
1      [(Job, NNP), (Title, NNP), (:, :), (Data, NNP)...
2      [(If, IN), (you, PRP), (are, VBP), (a, DT), (D...
3      [(Introduction, NN), (Uncover, NNP), (and, CC)...
4      [(If, IN), (you, PRP), (are, VBP), (a, DT), (S...
                             ...
246    [(DATA, NNP), (SCIENTIST, NNP), (Company, NNP)...
247    [(Our, PRP$), (client, NN), (,, ,), (a, DT), (...
248    [(Senior, NNP), (Data, NNP), (Scientist, NNP),...
249    [(TECHNOLOGY, NNP), (Ericsson, NNP), (Inc., NN...
250    [(A, DT), (client, NN), (of, IN), (Sharp, NNP)...
Name: Description, Length: 251, dtype: object

In [71]:
def noun_count(pos_tokens):
    nouns = []

    for tok in pos_tokens:
        if ( tok[1] in ('NN', 'NNS', 'NNP', 'NNPS') ) and ( tok[0].lower() not in stopwords.words('english')):
            nouns.append(tok[0].lower())
            
    word_count = {i:nouns.count(i) for i in set(nouns)}
    
    return word_count

In [72]:
job_count = job_tokens.apply(lambda x: noun_count(x))

In [73]:
job_count

0      {'background': 2, 'passion': 1, 'chance': 1, '...
1      {'vision': 1, 'background': 2, 'source': 1, 'a...
2      {'needs': 1, 'r': 1, 'insights': 1, 'technolog...
3      {'insights': 2, 'media': 2, 'orientation': 1, ...
4      {'clearance': 1, 'edge': 1, 'today': 1, 'senio...
                             ...
246    {'extraction': 1, '@': 1, 'twitter': 1, 'educa...
247    {'understanding': 2, 'testing': 2, 'r': 1, 'de...
248    {'eng': 2, 'amount': 1, 'econ': 2, 'amp': 4, '...
249    {'technologies': 1, 'ca': 1, 'work': 1, 'plano...
250    {'r': 1, 'insights': 1, 'technologies': 1, 'au...
Name: Description, Length: 251, dtype: object

In [78]:
def noun_set(pos_tokens):
    nouns = []

    for tok in pos_tokens:
        if ( tok[1] in ('NN', 'NNS', 'NNP', 'NNPS') ) and ( tok[0].lower() not in stopwords.words('english')):
            nouns.append(tok[0].lower())
            
    word_count = Counter({i:1 for i in set(nouns)})
    
    return word_count

In [79]:
job_set = job_tokens.apply(lambda x: noun_set(x))

In [80]:
job_set

0      {'background': 1, 'passion': 1, 'chance': 1, '...
1      {'vision': 1, 'background': 1, 'source': 1, 'a...
2      {'needs': 1, 'r': 1, 'insights': 1, 'technolog...
3      {'insights': 1, 'media': 1, 'orientation': 1, ...
4      {'clearance': 1, 'edge': 1, 'today': 1, 'senio...
                             ...
246    {'extraction': 1, '@': 1, 'twitter': 1, 'educa...
247    {'understanding': 1, 'testing': 1, 'r': 1, 'de...
248    {'eng': 1, 'amount': 1, 'econ': 1, 'amp': 1, '...
249    {'technologies': 1, 'ca': 1, 'work': 1, 'plano...
250    {'r': 1, 'insights': 1, 'technologies': 1, 'au...
Name: Description, Length: 251, dtype: object

In [83]:
job_set_count = Counter({})

for i in np.arange(len(job_set)):
    job_set_count += job_set[i]

In [86]:
job_set_count.most_common(150)

[('data', 248),
 ('experience', 237),
 ('science', 210),
 ('team', 187),
 ('years', 186),
 ('work', 167),
 ('python', 167),
 ('skills', 167),
 ('business', 155),
 ('engineering', 155),
 ('opportunity', 148),
 ('development', 146),
 ('tools', 140),
 ('machine', 137),
 ('ability', 136),
 ('computer', 136),
 ('company', 132),
 ('learning', 131),
 ('requirements', 129),
 ('position', 129),
 ('scientist', 128),
 ('models', 121),
 ('degree', 121),
 ('analytics', 121),
 ('job', 119),
 ('knowledge', 118),
 ('sql', 117),
 ('software', 117),
 ('design', 115),
 ('technology', 113),
 ('systems', 112),
 ('solutions', 112),
 ('information', 110),
 ('employment', 109),
 ('environment', 109),
 ('teams', 109),
 ('product', 108),
 ('analysis', 106),
 ('responsibilities', 105),
 ('statistics', 99),
 ('communication', 98),
 ('problems', 97),
 ('status', 97),
 ('employer', 96),
 ('qualifications', 95),
 ('understanding', 94),
 ('role', 94),
 ('orientation', 93),
 ('disability', 92),
 ('people', 92),
 ('ca', 92),
 ('industry', 91),
 ('management', 91),
 ('field', 91),
 ('’', 91),
 ('gender', 90),
 ('r', 89),
 ('race', 89),
 ('applicants', 88),
 ('techniques', 88),
 ('color', 88),
 ('origin', 87),
 ('services', 86),
 ('insights', 86),
 ('veteran', 86),
 ('opportunities', 86),
 ('religion', 86),
 ('identity', 86),
 ('projects', 85),
 ('age', 84),
 ('scientists', 83),
 ('world', 82),
 ('products', 81),
 ('location', 78),
 ('san', 78),
 ('research', 78),
 ('engineers', 76),
 ('technologies', 74),
 ('expertise', 72),
 ('mathematics', 72),
 ('group', 70),
 ('growth', 69),
 ('time', 69),
 ('platform', 69),
 ('application', 67),
 ('results', 66),
 ('client', 66),
 ('support', 66),
 ('sex', 66),
 ('applications', 65),
 ('building', 65),
 ('benefits', 63),
 ('algorithms', 63),
 ('visualization', 63),
 ('practices', 62),
 ('quality', 62),
 ('use', 62),
 ('needs', 61),
 ('operations', 61),
 ('impact', 61),
 ('bachelor', 61),
 ('methods', 61),
 ('passion', 60),
 ('stakeholders', 60),
 ('cloud', 60),
 ('project', 60),
 ('francisco', 60),
 ('modeling', 60),
 ('process', 60),
 ('processes', 59),
 ('education', 59),
 ('manner', 58),
 ('part', 57),
 ('aws', 57),
 ('languages', 57),
 ('today', 56),
 ('familiarity', 56),
 ('concepts', 56),
 ('/', 56),
 ('develop', 56),
 ('customer', 55),
 ('sets', 55),
 ('performance', 54),
 ('code', 54),
 ('partners', 54),
 ('customers', 54),
 ('description', 54),
 ('production', 53),
 ('platforms', 53),
 ('regard', 53),
 ('spark', 53),
 ('strong', 53),
 ('organization', 53),
 ('processing', 53),
 ('california', 53),
 ('career', 52),
 ('decisions', 52),
 ('candidate', 52),
 ('way', 51),
 ('members', 51),
 ('build', 51),
 ('employees', 50),
 ('java', 50),
 ('engineer', 49),
 ('intelligence', 49),
 ('@', 49),
 ('language', 49),
 ('value', 49),
 ('background', 48),
 ('vision', 48)]